from __future__ import annotations

# ============================================================
# Localization System
# ============================================================

TRANSLATIONS = {
    "en": {
        "app_title": "Prime Autoclicker", "home": "Home", "preset": "Preset",
        "settings": "Settings", "stats": "Stats", "other_projects": "Plugins",
        "log_in": "Log in", "achievements": "Achievements", "macro_builder": "Macro Builder", "support_hub": "Support Hub",
        "preset_builder": "Preset + Builder", "projects_about": "Projects + About", "admin": "Admin",
        "workflow_studio": "Workflow Studio",
        "start": "▶  Start", "stop": "■  Stop",
        "running": "● Running", "stopped": "● Stopped",
        "single_target": "Single Target Clicking",
        "single_target_sub": "Automatically click on one spot with precision. Simple, fast, and\nperfect for repetitive clicking tasks!",
        "event_timing": "Event Timing", "never_stop": "Never Stop",
        "num_cycles": "Number of Cycles", "time_gated": "Time Gated",
        "clicking_interval": "Clicking Interval", "time_interval": "Time Interval",
        "mouse_button": "Mouse Button", "left_click": "Left Click",
        "right_click": "Right Click", "middle_click": "Middle Click",
        "click_position": "Click Position", "follow_mouse": "Follow Mouse",
        "custom_position": "Custom Position",
        "follow_hint": "Follow Mouse: clicks wherever the cursor is.\nCustom Position: clicks at fixed X,Y coordinates.",
        "scroll_automation": "Scroll Wheel", "scroll_enable": "Enable Scroll Mode",
        "scroll_up": "Scroll Up", "scroll_down": "Scroll Down", "scroll_lines": "Lines per tick",
        "multi_button": "Multi-Button",
        "combo_single": "Single", "combo_alternate": "Alternate", "combo_double": "Simultaneous",
        "combo_hint": "Single: one button. Alternate: cycle L/R. Simultaneous: L+R together.",
        "position_offset": "Position Offset",
        "offset_hint": "Adds random ±px offset to each click position for human-like behavior.",
        "settings_title": "Settings",
        "settings_sub": "Customize sounds, delays, and clicking behavior.",
        "sound_effects": "Sound Effects", "start_stop_sound": "Start/Stop Sound",
        "per_click_sound": "Per-Click Tick Sound",
        "per_click_desc": "Play a subtle tick on every click.",
        "preview_sound": "🔈  Preview Sound",
        "advanced": "Advanced", "random_jitter": "Random Jitter (humanize clicks)",
        "jitter_desc": "Adds random variation to click interval to appear more human.",
        "delayed_start": "Delayed Start",
        "delay_desc": "Wait before clicking begins after pressing the hotkey.",
        "startup_windows": "Start with Windows",
        "startup_desc": "Launch Prime Autoclicker automatically when Windows starts.",
        "language": "Language",
        "profiles": "Profiles",
        "profiles_sub": "Save and load your favorite clicking configurations.",
        "new_preset": "＋  New Preset", "saved_presets": "Saved Presets",
        "load": "▶  Load", "delete": "🗑  Delete",
        "save_preset": "Save Preset", "preset_name": "Preset Name",
        "desc_optional": "Description (optional)", "cancel": "Cancel",
        "click_analytics": "Click Analytics",
        "analytics_sub": "Your clicking journey, tracked and visualized.",
        "all_time": "All-Time Clicks", "today": "Today",
        "this_week": "This Week", "this_month": "This Month",
        "last_7_days": "Last 7 Days", "milestones": "Milestones",
        "total_sessions": "Total Sessions", "avg_session": "Avg Clicks/Session",
        "best_day": "Best Day", "active_time": "Total Active Time",
        "tracking_since": "Tracking Since", "peak_hour": "Peak Hour",
        "click_heatmap": "Click Heatmap",
        "no_click_data": "No click data yet. Start clicking!",
        "cpu_perf": "Performance", "click_latency": "Click Latency", "cpu_usage": "CPU Usage",
        "achievements_sub": "Your clicking milestones and badges.",
        "warn_interval": "Setting the click interval to less than 1 millisecond may\ncause your device to freeze or behave abnormally.",
        "another_fact": "🎲  Another fact!",
        "milliseconds": "Milliseconds", "seconds": "Seconds",
        "minutes": "Minutes", "hours": "Hours",
        "none_sound": "None", "default_beep": "Default Beep",
        "ding": "Ding", "chirp": "Chirp", "alert": "Alert",
        "hotkey_profiles": "Hotkey Profiles",
        "hotkey_profiles_desc": "Assign a keyboard shortcut to each preset for instant switching.",
        "assign_hotkey": "Assign Hotkey",
        "scroll_keybind": "Scroll Keybind",
        "scroll_keybind_desc": "Press this key to toggle scroll automation on/off.",
    },
    "de": {
        "app_title": "Prime Autoclicker", "home": "Startseite", "preset": "Vorlagen",
        "settings": "Einstellungen", "stats": "Statistiken", "other_projects": "Plugins",
        "log_in": "Anmelden", "achievements": "Erfolge", "macro_builder": "Macro Builder", "support_hub": "Support Hub",
        "preset_builder": "Vorlagen + Builder", "projects_about": "Projekte + About", "admin": "Admin",
        "workflow_studio": "Workflow Studio",
        "start": "▶  Start", "stop": "■  Stopp",
        "running": "● Läuft", "stopped": "● Gestoppt",
        "single_target": "Einzel-Ziel-Klicken",
        "single_target_sub": "Automatisch auf einen Punkt klicken mit Präzision. Einfach, schnell\nund perfekt für wiederholende Klickaufgaben!",
        "event_timing": "Ereignis-Timing", "never_stop": "Nie stoppen",
        "num_cycles": "Anzahl Zyklen", "time_gated": "Zeitbegrenzt",
        "clicking_interval": "Klickintervall", "time_interval": "Zeitintervall",
        "mouse_button": "Maustaste", "left_click": "Linksklick",
        "right_click": "Rechtsklick", "middle_click": "Mittelklick",
        "click_position": "Klickposition", "follow_mouse": "Maus folgen",
        "custom_position": "Benutzerdefiniert",
        "follow_hint": "Maus folgen: klickt wo der Cursor ist.\nBenutzerdefiniert: klickt auf feste X,Y-Koordinaten.",
        "scroll_automation": "Scrollrad", "scroll_enable": "Scroll-Modus aktivieren",
        "scroll_up": "Nach oben", "scroll_down": "Nach unten", "scroll_lines": "Zeilen pro Tick",
        "multi_button": "Multi-Taste",
        "combo_single": "Einzeln", "combo_alternate": "Abwechselnd", "combo_double": "Gleichzeitig",
        "combo_hint": "Einzeln: eine Taste. Abwechselnd: L/R wechselnd. Gleichzeitig: L+R zusammen.",
        "position_offset": "Positionsversatz",
        "offset_hint": "Fügt zufälligen ±px Versatz hinzu für menschliches Verhalten.",
        "settings_title": "Einstellungen",
        "settings_sub": "Töne, Verzögerungen und Klickverhalten anpassen.",
        "sound_effects": "Soundeffekte", "start_stop_sound": "Start/Stopp-Ton",
        "per_click_sound": "Klick-Tick-Ton",
        "per_click_desc": "Spielt bei jedem Klick einen leisen Tick.",
        "preview_sound": "🔈  Vorschau",
        "advanced": "Erweitert", "random_jitter": "Zufalls-Jitter (menschlich wirken)",
        "jitter_desc": "Fügt zufällige Variation zum Klickintervall hinzu.",
        "delayed_start": "Verzögerter Start",
        "delay_desc": "Wartet vor dem Klicken nach Drücken der Taste.",
        "startup_windows": "Mit Windows starten",
        "startup_desc": "Prime Autoclicker automatisch beim Windows-Start öffnen.",
        "language": "Sprache",
        "profiles": "Profile",
        "profiles_sub": "Lieblingseinstellungen speichern und laden.",
        "new_preset": "＋  Neue Vorlage", "saved_presets": "Gespeicherte Vorlagen",
        "load": "▶  Laden", "delete": "🗑  Löschen",
        "save_preset": "Vorlage speichern", "preset_name": "Vorlagenname",
        "desc_optional": "Beschreibung (optional)", "cancel": "Abbrechen",
        "click_analytics": "Klick-Analyse",
        "analytics_sub": "Deine Klickreise, verfolgt und visualisiert.",
        "all_time": "Alle Klicks", "today": "Heute",
        "this_week": "Diese Woche", "this_month": "Diesen Monat",
        "last_7_days": "Letzte 7 Tage", "milestones": "Meilensteine",
        "total_sessions": "Sitzungen gesamt", "avg_session": "Ø Klicks/Sitzung",
        "best_day": "Bester Tag", "active_time": "Aktive Zeit gesamt",
        "tracking_since": "Erfassung seit", "peak_hour": "Spitzenstunde",
        "click_heatmap": "Klick-Heatmap",
        "no_click_data": "Noch keine Klickdaten. Fang an zu klicken!",
        "cpu_perf": "Leistung", "click_latency": "Klick-Latenz", "cpu_usage": "CPU-Auslastung",
        "achievements_sub": "Deine Klick-Meilensteine und Abzeichen.",
        "warn_interval": "Ein Klickintervall unter 1 Millisekunde kann\ndein Gerät einfrieren lassen.",
        "another_fact": "🎲  Noch ein Fakt!",
        "milliseconds": "Millisekunden", "seconds": "Sekunden",
        "minutes": "Minuten", "hours": "Stunden",
        "none_sound": "Keiner", "default_beep": "Standard-Piep",
        "ding": "Ding", "chirp": "Zwitschern", "alert": "Alarm",
        "hotkey_profiles": "Hotkey-Profile",
        "hotkey_profiles_desc": "Weisen Sie jedem Profil eine Tastenkombination zu.",
        "assign_hotkey": "Hotkey zuweisen",
        "scroll_keybind": "Scroll-Taste",
        "scroll_keybind_desc": "Diese Taste dr\u00fccken, um Scroll-Automatik ein/auszuschalten.",
    },
    "fr": {
        "app_title": "Prime Autoclicker", "home": "Accueil", "preset": "Pr\u00e9r\u00e9glages",
        "settings": "Param\u00e8tres", "stats": "Statistiques", "other_projects": "Plugins",
        "log_in": "Connexion", "achievements": "Succès", "macro_builder": "Macro Builder", "support_hub": "Support Hub",
        "preset_builder": "Pr\u00e9r\u00e9glages + Builder", "projects_about": "Projets + About", "admin": "Admin",
        "workflow_studio": "Workflow Studio",
        "start": "▶  Démarrer", "stop": "■  Arrêter",
        "running": "● En cours", "stopped": "● Arrêté",
        "single_target": "Clic Cible Unique",
        "single_target_sub": "Cliquer automatiquement sur un point avec précision. Simple, rapide\net parfait pour les tâches de clic répétitives !",
        "event_timing": "Minuterie", "never_stop": "Ne jamais arrêter",
        "num_cycles": "Nombre de cycles", "time_gated": "Limité dans le temps",
        "clicking_interval": "Intervalle de clic", "time_interval": "Intervalle",
        "mouse_button": "Bouton de souris", "left_click": "Clic gauche",
        "right_click": "Clic droit", "middle_click": "Clic milieu",
        "click_position": "Position du clic", "follow_mouse": "Suivre la souris",
        "custom_position": "Position fixe",
        "follow_hint": "Suivre la souris : clique où se trouve le curseur.\nPosition fixe : clique aux coordonnées X,Y fixes.",
        "scroll_automation": "Molette", "scroll_enable": "Activer le défilement",
        "scroll_up": "Vers le haut", "scroll_down": "Vers le bas", "scroll_lines": "Lignes par tick",
        "multi_button": "Multi-Bouton",
        "combo_single": "Simple", "combo_alternate": "Alterner", "combo_double": "Simultané",
        "combo_hint": "Simple : un bouton. Alterner : cycle G/D. Simultané : G+D ensemble.",
        "position_offset": "Décalage de position",
        "offset_hint": "Ajoute un décalage aléatoire ±px pour un comportement humain.",
        "settings_title": "Paramètres",
        "settings_sub": "Personnaliser les sons, délais et comportement.",
        "sound_effects": "Effets sonores", "start_stop_sound": "Son Démarrer/Arrêter",
        "per_click_sound": "Son par clic",
        "per_click_desc": "Jouer un petit tick à chaque clic.",
        "preview_sound": "🔈  Aperçu",
        "advanced": "Avancé", "random_jitter": "Gigue aléatoire (humaniser)",
        "jitter_desc": "Ajoute une variation aléatoire à l'intervalle de clic.",
        "delayed_start": "Démarrage différé",
        "delay_desc": "Attendre avant de commencer à cliquer.",
        "startup_windows": "Démarrer avec Windows",
        "startup_desc": "Lancer Prime Autoclicker au démarrage de Windows.",
        "language": "Langue",
        "profiles": "Profils",
        "profiles_sub": "Sauvegarder et charger vos configurations préférées.",
        "new_preset": "＋  Nouveau", "saved_presets": "Préréglages sauvegardés",
        "load": "▶  Charger", "delete": "🗑  Supprimer",
        "save_preset": "Sauvegarder", "preset_name": "Nom du préréglage",
        "desc_optional": "Description (optionnel)", "cancel": "Annuler",
        "click_analytics": "Analyse des clics",
        "analytics_sub": "Votre parcours de clics, suivi et visualisé.",
        "all_time": "Total des clics", "today": "Aujourd'hui",
        "this_week": "Cette semaine", "this_month": "Ce mois",
        "last_7_days": "7 derniers jours", "milestones": "Jalons",
        "total_sessions": "Sessions totales", "avg_session": "Moy. clics/session",
        "best_day": "Meilleur jour", "active_time": "Temps actif total",
        "tracking_since": "Suivi depuis", "peak_hour": "Heure de pointe",
        "click_heatmap": "Carte thermique",
        "no_click_data": "Pas encore de données. Commencez à cliquer !",
        "cpu_perf": "Performance", "click_latency": "Latence de clic", "cpu_usage": "Utilisation CPU",
        "achievements_sub": "Vos jalons et badges de clic.",
        "warn_interval": "Un intervalle inférieur à 1 ms peut\nfaire geler votre appareil.",
        "another_fact": "🎲  Autre fait !",
        "milliseconds": "Millisecondes", "seconds": "Secondes",
        "minutes": "Minutes", "hours": "Heures",
        "none_sound": "Aucun", "default_beep": "Bip par défaut",
        "ding": "Ding", "chirp": "Gazouillis", "alert": "Alerte",
        "hotkey_profiles": "Profils raccourcis",
        "hotkey_profiles_desc": "Attribuer un raccourci clavier à chaque profil.",
        "assign_hotkey": "Attribuer raccourci",
        "scroll_keybind": "Touche de d\u00e9filement",
        "scroll_keybind_desc": "Appuyer pour activer/d\u00e9sactiver le d\u00e9filement automatique.",
    },
    "es": {
        "app_title": "Prime Autoclicker", "home": "Inicio", "preset": "Perfiles",
        "settings": "Ajustes", "stats": "Estadisticas", "other_projects": "Plugins",
        "log_in": "Acerca de", "achievements": "Logros", "macro_builder": "Macro Builder", "support_hub": "Centro de Soporte",
        "preset_builder": "Perfiles + Builder", "projects_about": "Proyectos + About", "admin": "Admin",
        "workflow_studio": "Workflow Studio",
        "start": "▶  Iniciar", "stop": "■  Detener",
        "running": "● Activo", "stopped": "● Detenido",
        "settings_title": "Ajustes", "settings_sub": "Personaliza sonidos, retrasos y comportamiento.",
        "sound_effects": "Sonidos", "start_stop_sound": "Sonido de inicio/parada",
        "per_click_desc": "Reproducir tick en cada clic.", "preview_sound": "🔈  Vista previa",
        "advanced": "Avanzado", "random_jitter": "Jitter aleatorio", "jitter_desc": "Variacion aleatoria del intervalo.",
        "delayed_start": "Inicio con retraso", "delay_desc": "Espera antes de empezar.",
        "startup_windows": "Iniciar con Windows", "startup_desc": "Abrir automaticamente con Windows.",
        "language": "Idioma", "profiles": "Perfiles", "profiles_sub": "Guardar y cargar configuraciones.",
        "new_preset": "＋  Nuevo Perfil", "saved_presets": "Perfiles guardados",
        "load": "▶  Cargar", "delete": "🗑  Eliminar",
        "click_analytics": "Analitica", "analytics_sub": "Tu progreso de clics.",
        "all_time": "Total", "today": "Hoy", "this_week": "Esta semana", "this_month": "Este mes",
        "last_7_days": "Ultimos 7 dias", "milestones": "Hitos",
        "click_heatmap": "Mapa de calor", "cpu_perf": "Rendimiento", "click_latency": "Latencia",
        "none_sound": "Ninguno", "default_beep": "Pitido",
        "ding": "Ding", "chirp": "Chirp", "alert": "Alerta",
        "scroll_keybind": "Tecla de scroll", "scroll_keybind_desc": "Pulsa esta tecla para activar/desactivar scroll.",
        "milliseconds": "Milisegundos", "seconds": "Segundos", "minutes": "Minutos", "hours": "Horas",
    },
}

_current_lang = "en"


def tr(key: str) -> str:
    return TRANSLATIONS.get(_current_lang, TRANSLATIONS["en"]).get(key, TRANSLATIONS["en"].get(key, key))


def set_language(lang: str):
    global _current_lang
    if lang in TRANSLATIONS:
        _current_lang = lang
